# Generated by Django 4.1.2 on 2022-11-02 05:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('department', models.CharField(choices=[('CSCE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Electrical Engineering')], max_length=10)),
                ('year', models.IntegerField(blank=True)),
                ('semester', models.CharField(choices=[('Fall', 'Fall'), ('SPRING', 'Spring'), ('SUMMER', 'Summer')], max_length=10)),
                ('credits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('type', models.CharField(choices=[('student', 'student'), ('professor', 'professor'), ('staff', 'staff'), ('admin', 'admin')], max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('CSCE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Electrical Engineering')], default='', max_length=10)),
                ('phone', models.CharField(max_length=50)),
                ('dateAdded', models.DateField(default=datetime.date.today)),
                ('courses', models.ManyToManyField(to='gradebook_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gradebook_app.profile')),
                ('title', models.CharField(max_length=50)),
            ],
            bases=('gradebook_app.profile',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gradebook_app.profile')),
                ('degree', models.CharField(max_length=50)),
                ('gpa', models.FloatField()),
            ],
            bases=('gradebook_app.profile',),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_id', models.CharField(max_length=10, unique=True)),
                ('eval_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('max_score', models.IntegerField()),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('due_by', models.DateField(default=datetime.date.today)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook_app.course')),
            ],
        ),
    ]
