# Generated by Django 4.1.2 on 2022-11-14 00:56

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('department', models.CharField(choices=[('CSCE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Electrical Engineering')], max_length=100)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2022), django.core.validators.MinValueValidator(2023)])),
                ('semester', models.CharField(choices=[('Fall', 'Fall'), ('SPRING', 'Spring'), ('SUMMER', 'Summer')], max_length=10)),
                ('credits', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('max_score', models.FloatField(default=0)),
                ('min_score', models.FloatField(default=0)),
                ('mean_score', models.FloatField(default=0)),
                ('thresholds', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eval_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('max_marks', models.IntegerField()),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('type', models.CharField(choices=[('student', 'student'), ('professor', 'professor'), ('staff', 'staff'), ('admin', 'admin')], max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('department', models.CharField(choices=[('CSCE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Electrical Engineering')], max_length=100)),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='Phone number must be numeric', regex='[0-9]+')])),
                ('date_added', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook_app.course')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook_app.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='courses',
            field=models.ManyToManyField(related_name='profiles', through='gradebook_app.ProfileCourse', to='gradebook_app.course'),
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField(default=0)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook_app.course')),
                ('eval_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook_app.evaluation')),
                ('profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gradebook_app.profile')),
            ],
        ),
    ]
