# Generated by Django 4.1.2 on 2022-10-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('student', 'student'), ('professor', 'professor'), ('staff', 'staff'), ('admin', 'admin')], max_length=10)),
            ],
        ),
    ]
