# Generated by Django 4.1.2 on 2022-11-04 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook_app', '0002_enrollment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='profile_id',
            new_name='profile',
        ),
    ]
