# Generated by Django 4.1.2 on 2022-11-25 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook_app', '0003_rename_eval_id_marks_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2022), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
