# Generated by Django 4.1.2 on 2022-11-05 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook_app', '0003_rename_course_id_enrollment_course_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
