# Generated by Django 4.1.2 on 2022-11-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook_app', '0004_alter_course_course_code_alter_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('STUDENT', 'student'), ('PROFESSOR', 'professor'), ('ADMIN', 'admin')], max_length=10),
        ),
    ]
