# Generated by Django 4.1.2 on 2022-12-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook_app', '0006_alter_course_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='course',
            name='mean_score',
        ),
        migrations.RemoveField(
            model_name='course',
            name='min_score',
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('Fall', 'Fall'), ('SPRING', 'Spring'), ('SUMMER', 'Summer')], max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('student', 'student'), ('professor', 'professor'), ('admin', 'admin')], max_length=10),
        ),
    ]
